title: Gunner is the Best
author: GitHub User
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
Gunner is the best dog in the world. He is so snuggly and sweet.

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
